version: '2.2'
services:
  db:
    image: 'postgres:10.1-alpine'
    environment:
      POSTGRES_PASSWORD: '${DB_PW}'
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_DB: '${DB_NAME}'
    ports:
      - '5432:5432'
    networks:
      - dockernet1
  postgraphql:
    image: erasche/postgraphql
    ports:
      - '5000:5000'
    environment:
      DB_GRAPHQL_PATH: /graphql
      DB_GRAPHIQL_PATH: /graphiql
      PG_SECRET: '${JWT_SECRET}'
      DB_SCHEMA: '${DB_SCHEMA}'
      PGUSER: '${DB_USER}'
      PGPASSWORD: '${DB_PW}'
      PGHOST: db
      PGPORT: 5432
      PGDATABASE: '${DB_NAME}'
    networks:
      - dockernet1
    links:
      - db
networks:
  dockernet1: null
