version: '2.2'
services:
  db:
    image: 'postgres:10.1-alpine'
    environment:
      POSTGRES_PASSWORD: '${PGPASSWORD}'
      POSTGRES_USER: '${PGUSER}'
      POSTGRES_DB: '${PGDATABASE}'
    ports:
      - '5432:5432'
    networks:
      - dockernet1
  migrations:
    build: ./migrations
    environment:
      PGHOST: db
      PGUSER: '${PGUSER}'
      PGPASSWORD: '${PGPASSWORD}'
      PGDATABASE: '${PGDATABASE}'
    volumes:
      - './migrations/sql:/flyway/sql'
    networks:
      - dockernet1
    depends_on:
      - db
  postgraphql:
    image: erasche/postgraphql
    init: true
    user: node
    ports:
      - '5000:5000'
    depends_on:
      - db
    environment:
      DB_GRAPHQL_PATH: /graphql
      DB_GRAPHIQL_PATH: /graphiql
      PG_SECRET: '${JWT_SECRET}'
      DB_SCHEMA: '${DB_SCHEMA}'
      PGUSER: '${PGUSER}'
      PGPASSWORD: '${PGPASSWORD}'
      PGHOST: db
      PGPORT: 5432
      PGDATABASE: '${PGDATABASE}'
    networks:
      - dockernet1
networks:
  dockernet1: null
