version: '2.2'
services:
  db:
    image: 'postgres:10.1-alpine'
    environment:
      POSTGRES_PASSWORD: '${PGPASSWORD}'
      POSTGRES_USER: '${PGUSER}'
      POSTGRES_DB: '${DB_NAME}'
    ports:
      - 5432:5432
  migrations:
    build: ./migrations
    environment:
      PGHOST: db
      PGUSER: '${PGUSER}'
      PGPASSWORD: '${PGPASSWORD}'
    entrypoint: [ "wait-for-postgres.sh", "flyway", "-url=jdbc:postgresql://db:5432/${DB_NAME}", "-schemas=${DB_SCHEMA}", "-user=${PGUSER}", "-password=${PGPASSWORD}", "migrate" ]
    volumes:
      - ./migrations/sql:/flyway/sql
    links:
      - db
  postgraphql:
    image: erasche/postgraphql
    ports:
      - '5000:5000'
    environment:
      DB_GRAPHQL_PATH: /graphql
      DB_GRAPHIQL_PATH: /graphiql
      PG_SECRET: '${JWT_SECRET}'
      DB_SCHEMA: '${DB_SCHEMA}'
      PGUSER: '${PGUSER}'
      PGPASSWORD: '${PGPASSWORD}'
      PGHOST: db
      PGPORT: 5432
      PGDATABASE: '${DB_NAME}'
    links:
      - db
