version: '2.2'
services:
  db:
    image: 'postgres:10.1-alpine'
    environment:
      POSTGRES_PASSWORD: '${PGPASSWORD}'
      POSTGRES_USER: '${PGUSER}'
      POSTGRES_DB: '${PGDATABASE}'
    ports:
      - '5432:5432'
    networks:
      - dockernet1
  migrations:
    build: ./migrations
    environment:
      PGHOST: db
      PGUSER: '${PGUSER}'
      PGPASSWORD: '${PGPASSWORD}'
      PGDATABASE: '${PGDATABASE}'
    volumes:
      - './migrations/sql:/flyway/sql'
    networks:
      - dockernet1
    depends_on:
      - db
  postgraphql:
    build: .
    volumes:
      - './:/app'
    init: true
    ports:
      - '5000:5000'
      - '9229:9229'
    depends_on:
      - db
    environment:
      DB_GRAPHQL_PATH: /graphql
      DB_GRAPHIQL_PATH: /graphiql
      PGHOST: db
      PGPORT: 5432
      JWT_SECRET: '${JWT_SECRET}'
      DB_SCHEMA: '${DB_SCHEMA}'
      PGUSER: '${PGUSER}'
      PGPASSWORD: '${PGPASSWORD}'
      PGDATABASE: '${PGDATABASE}'
      JWT_AUDIENCES: '${JWT_AUDIENCES}'
      FACEBOOK_CLIENT_ID: '${FACEBOOK_CLIENT_ID}'
      FACEBOOK_CLIENT_SECRET: '${FACEBOOK_CLIENT_SECRET}'
      SERVER_URL: '${SERVER_URL}'
      COOKIE_SECRET: '${COOKIE_SECRET}'
    networks:
      - dockernet1
networks:
  dockernet1: null
