version: '2.2'
services:
  db:
    image: "postgres:10.1-alpine"
    environment:
     POSTGRES_PASSWORD: ${DB_PW}
     POSTGRES_USER: ${DB_USER}
     POSTGRES_DB: ${DB_NAME}
    ports:
     - "5432:5432"
    networks:
     - dockernet1 
networks:
    dockernet1:

