version: '2.2'
services:
  db:
    image: 'clkao/postgres-plv8:9.6-1.5'
    env_file: '.env'
    environment:
      POSTGRES_PASSWORD: '${PGPASSWORD}'
      POSTGRES_USER: '${PGUSER}'
      POSTGRES_DB: '${PGDATABASE}'
    ports:
      - '5432:5432'
    networks:
      - dockernet1
    healthcheck:
      test: 'pg_isready -U postgres'
      interval: 5s
      timeout: 10s
      retries: 12
  postgraphql:
    build: .
    volumes:
      - './migrations:/app/migrations'
      - './src:/app/src'
      - './package.json:/app/package.json'
    init: true
    ports:
      - '5000:5000'
      - '9229:9229'
    depends_on:
      db:
        condition: service_healthy
    env_file: '.env'
    command: 'npm run start-debug'
    environment:
      DO_MIGRATIONS: 'true'
      PGHOST: db
      PGPORT: 5432
      JWT_SECRET: '${JWT_SECRET}'
      DB_SCHEMA: '${DB_SCHEMA}'
      PGUSER: '${PGUSER}'
      PGPASSWORD: '${PGPASSWORD}'
      PGDATABASE: '${PGDATABASE}'
      JWT_AUDIENCES: '${JWT_AUDIENCES}'
      FACEBOOK_CLIENT_ID: '${FACEBOOK_CLIENT_ID}'
      FACEBOOK_CLIENT_SECRET: '${FACEBOOK_CLIENT_SECRET}'
      SERVER_URL: '${SERVER_URL}'
      COOKIE_SECRET: '${COOKIE_SECRET}'
      COOKIE_DOMAIN: '${COOKIE_DOMAIN}'
      PG_DEFAULT_ROLE: '${PG_DEFAULT_ROLE}'
    networks:
      - dockernet1
networks:
  dockernet1: null
