version: '2.2'
services:
  db:
    image: "postgres:10.1-alpine"
    environment:
     POSTGRES_PASSWORD: ${DB_PW}
     POSTGRES_USER: ${DB_USER}
     POSTGRES_DB: ${DB_NAME}
    networks:
     - dockernet1 
  web:
    build: .
    command: npm run start
    ports:
     - "3000:3000"
    volumes:
     - .:/usr/src/app
     - /usr/src/app/node_modules
     - /tmp/root:/root
    depends_on:
     - "db"
    environment:
    - DB_HOST=db
    - DB_USER=${DB_USER}
    - DB_PW=${DB_PW}
    - DB_NAME=${DB_NAME}
    networks:
    - dockernet1
networks:
    dockernet1:

